# This is a basic workflow to help you get started with Actions

name: Copy JSON

on:
  schedule:
    - cron: "15 0,2,12 * * *"

jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout pomber/covid19 repo
        uses: actions/checkout@v2
        with:
          repository: pomber/covid19
          path: pomber
      - name: Copy timeseries from pomber
        run: \cp pomber/docs/timeseries.json main/src/assets/timeseries.json
      - name: Commit files
        run: |
          cd main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update json" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main
