name: Update data and build

on:
  schedule:
    - cron: "30 0,2,12 * * *"
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout pomber/covid19 repo
        uses: actions/checkout@v2
        with:
          repository: pomber/covid19
          path: pomber
      
      - name: Copy timeseries from pomber
        run: \cp pomber/docs/timeseries.json main/src/assets/timeseries.json
      
      - name: Node $
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install and npm run build
        run: |
          cd main
          npm ci
          npm run build
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update json" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main