name: Update data and build

on:
  # Run regularly
  schedule:
    - cron: "30 0,2,12 * * *"
  # Run on each commit apart from docs updates
  push:
    paths-ignore:
    - 'docs/**'
    - 'src/assets/timeseries.json'
  # Run on each issue (easy to trigger the workflow manually this way)
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout pomber/covid19 repo
        uses: actions/checkout@v2
        with:
          repository: pomber/covid19
          path: pomber
      
      - name: Copy timeseries.json from pomber
        run: \cp pomber/docs/timeseries.json main/src/assets/timeseries.json
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Build app to ./docs (intended to be served by Github pages)
        run: |
          cd main
          npm ci
          npm run build
      
      - name: Commit all changes to repo
        run: |
          cd main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update and build" -a
      
      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main
